fix: be more robust around task lifecycle
I do not understand what caused this issue, but somehow f48d166
introduced an error where tasks would report,

    error: wait: no child processes

I can't reproduce the error before that commit, and `run prerelease` (or
`run build`) consistently produces the error after it. This change
catches and ignores the error.

I feel very queasy about this change.